### ISSUE TITLE
[Question ] How can we implement Topic Modelling(for e.g - LDA) using tensorflow? 

### ISSUE THREAD

**Issue by mahatosourav91** [BinRoot/TensorFlow-Book#10]
I am trying to Topic Modelling (LDA) using tensorflow. But I could find any existing LDA implementation using tensorflow.
Is there any other way to implement Topic Modelling using tensorflow?
If there is any suitable example / implementation / guide of LDA using tensorflow , it would be very helpful

**Comment by BinRoot** [comment]
Not sure of any good tutorials on this topic. It's not covered in this book, but depending on time, I can add it as a supplementary chapter.

**Comment by sabudanakichdi** [comment]
This guy has used lda2vec in tensorflow for reference: https://github.com/meereeum/lda2vec-tf Adding a supplementary chapter would be helpful.
