### ISSUE TITLE
Clustering with self-organizing map

### ISSUE THREAD

**Issue by amit2103** [BinRoot/TensorFlow-Book#11]
Hi,

I bought the MEAP book and its great. 
We are trying to cluster some values with the algorithm. We would like  to get the label of each input to a cluster. So if there are 10 clusters and an input vector v, we would like to know which cluster does V belong to . Can you please let me know what are the changes required?

**Comment by BinRoot** [comment]
If you already know the number of clusters, a safe bet is to use K-means instead. Otherwise, [this article](http://lib.tkk.fi/Diss/2002/isbn951226093X/article4.pdf) explains a couple ways to find clusters in a SOM.
