### ISSUE TITLE
ch02_basics Concept06_saving_variables

### ISSUE THREAD

**Issue by toasteez** [BinRoot/TensorFlow-Book#3]
When running the following code from [code](https://github.com/BinRoot/TensorFlow-Book/blob/master/ch02_basics/Concept06_saving_variables.ipynb):

    save_path = saver.save(sess, "spikes.ckpt")
    print("spikes data saved in file: %s" % save_path)

I receive an error.

I am running on Windows 7 in conda virtual environment and Jupyter. 

    ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    <ipython-input-36-444ce612b9fd> in <module>()
    ----> 1 save_path = saver.save(sess, "spikes.ckpt")
          2 print("spikes data saved in file: %s" % save_path)

    C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\training\saver.py in save(self, sess, save_path, global_step, latest_filename, meta_graph_suffix, write_meta_graph, write_state)
       1312     if not gfile.IsDirectory(os.path.dirname(save_path)):
       1313       raise ValueError(
    -> 1314           "Parent directory of {} doesn't exist, can't save.".format(save_path))
       1315 
       1316     save_path = os.path.dirname(save_path)

    ValueError: Parent directory of spikes.ckpt doesn't exist, can't save.

**Comment by johndpope** [comment]
I recommend you provide an ubuntu virtual machine image link(not docker), rather than trying to get this code running on every machine.

**Comment by johndpope** [comment]
Try this

https://medium.com/@josemarcialportilla/hi-there-im-jose-portilla-and-i-teach-data-science-online-and-in-person-1c93298d5145#.b7be2cczt

**Comment by sicnarf1a** [comment]
I have the same issue. I am currently using windows10 and jupyter notebooks. To solve this problem, is it necessary to use in a virtual environment?

**Comment by chmnoh** [comment]
You may try absolute path, for example:
`"C:\\Users\\YourName\\Documents\\spikes.ckpt"`

**Comment by DiegoPortoJaccottet** [comment]
I got a similar problem in "Ch 02: Concept 07", couldn't load the variables until I used the full path: 
>>> try:
...     saver.restore(sess, 'spikes.ckpt')
...     print(spikes.eval())
... except:
...     print('file not found')
...
W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for spikes.ckpt
file not found
>>> try:
...     saver.restore(sess, os.path.abspath('spikes.ckpt'))
...     print(spikes.eval())
... except:
...     print('file not found')
...
[False False  True False False  True False  True]

**Comment by BinRoot** [comment]
Interesting. Have you tried running `restore` on ".spikes.ckpt"? It seems to work with the prefixed "."

**Comment by minkoon** [comment]
change the path to be exactly directory.
 For example:
 checkpoint_name = "C:\Users\Minkun\Desktop\VTIS_Project\model.ckpt"
 note that you used '\' instead ''
