### ISSUE TITLE
CH02 Concept 8 Warnings

### ISSUE THREAD

**Issue by toasteez** [BinRoot/TensorFlow-Book#4]
You may want to update code to fix warnings.

Fix:

    avg_hist = tf.summary.scalar("running_average", update_avg)
    value_hist = tf.summary.scalar("incoming_values", curr_value)

    merged = tf.summary.merge_all()
    writer = tf.summary.FileWriter("./logs")

    init = tf.global_variables_initializer()

    with tf.Session() as sess:
        sess.run(init)
        for i in range(len(raw_data)):
            summary_str, curr_avg = sess.run([merged, update_avg], feed_dict={curr_value: raw_data[i]})
            sess.run(tf.assign(prev_avg, curr_avg))
            print(raw_data[i], curr_avg)
            writer.add_summary(summary_str, i)

WARNING:tensorflow:From <ipython-input-39-3bc6f2926948>:1 in <module>.: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
WARNING:tensorflow:From <ipython-input-39-3bc6f2926948>:2 in <module>.: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
WARNING:tensorflow:From <ipython-input-39-3bc6f2926948>:4 in <module>.: merge_all_summaries (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.merge_all.
WARNING:tensorflow:From C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\logging_ops.py:264 in merge_all_summaries.: merge_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.merge.
WARNING:tensorflow:From <ipython-input-39-3bc6f2926948>:5 in <module>.: SummaryWriter.__init__ (from tensorflow.python.training.summary_io) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.FileWriter. The interface and behavior is the same; this is just a rename.

**Comment by sbshah97** [comment]
I faced the same issue!

**Comment by BinRoot** [comment]
Fixed! I updated the code to TensorFlow v1.0
