### ISSUE TITLE
A mistake in Concept01 in Chapter04

### ISSUE THREAD

**Issue by zhbzz2007** [BinRoot/TensorFlow-Book#6]
I am reading TensorFlow-Book/ch04_classification/Concept01_linear_regression_classification.ipynb , I find a mistake.

In your description

> Let's say we have numbers that we want to classify. They'll just be 1-dimensional values. Numbers close to 2 will be given the label [0], and numbers close to 5 will be given the label [1], as designed here:

but in your code,

```
x_label0 = np.random.normal(5, 1, 10)
x_label1 = np.random.normal(2, 1, 10)
print x_label0
print x_label1
xs = np.append(x_label0, x_label1)
labels = [0.] * len(x_label0) + [1.] * len(x_label1)
```

we can find you give Numbers close to 2 is label [1], and numbers close to 5 is label [0].

Maybe you need fix this mistake.

**Comment by BinRoot** [comment]
Thank you! Fixed! 4f96d49
