### ISSUE TITLE
Error during import of Tensorflow module post installation

### ISSUE THREAD

**Issue by namrathaurs** [BinRoot/TensorFlow-Book#8]
I happened to stumble upon your repository and the book which you are working towards. I guess going through the learning materials put together by you would help me a great deal to know and understand Tensorflow better. However, as much as I have been wanting to try a hands-on with Tensorflow, I am running into an issue when I import tensorflow module in Python.

So, if you could let me know if this might be the place where I could get some insights, I shall post my issue so that I can get some pointers to troubleshoot the issue. If not, can you please help me out by letting me know where would be the best place or who would be the best ones to help me with this?

P.S. Although I know what GitHub is basically used for, I am still slightly a beginner in using GitHub and its working model. This would give me a good opportunity to learn things the right way. So until then, please do pardon my way of communication.

Eagerly awaiting a positive reply from your end.

Thanks & Regards,
Namratha

**Comment by BinRoot** [comment]
Hi Namratha,

I'm not sure the root cause of your error.
Try the virtualenv installation method. https://www.tensorflow.org/install/install_linux#InstallingVirtualenv
