### ISSUE TITLE
Error in Concept06_saving_variables

### ISSUE THREAD

**Issue by iacolippo** [BinRoot/TensorFlow-Book#9]
When I run the code as it is, at the moment of saving (block 5), I get the following error:

```
FailedPreconditionError: Attempting to use uninitialized value Variable
	 [[Node: save_2/SaveV2 = SaveV2[dtypes=[DT_BOOL, DT_BOOL], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_2/Const_0, save_2/SaveV2/tensor_names, save_2/SaveV2/shape_and_slices, Variable, spikes)]]

Caused by op u'save_2/SaveV2', defined at:
```

I find that it is solved by modifying block 2 in:

`saver = tf.train.Saver([spikes])`

or

`saver = tf.train.Saver({'spikes': spikes})`

**Comment by BinRoot** [comment]
Hi @iacolippo or anyone else, could you take a look at the most recent [Concept06](https://github.com/BinRoot/TensorFlow-Book/blob/master/ch02_basics/Concept06_saving_variables.ipynb) to see if the errors go away?

**Comment by iacolippo** [comment]
Now it's working fine for me.

`tensorflow==1.0.1` and `MacOS 10.12.3`

**Comment by BinRoot** [comment]
Great, thanks!
